### ISSUE TITLE
SocketError Exception: getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by OktoberComstock** [copiousfreetime/torid#2]
Hi there, after updating to OS Sierra on my mac, I started running into this issue. I'm not sure if it's an issue in the gem, but I had to be sure because I'm at my wits end. 

When I try to run my full test suite locally for my app, I get this error trace:

`/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'torid'. (Bundler::GemRequireError)
Gem Load Error is: getaddrinfo: nodename nor servname provided, or not known
Backtrace for gem load error is:
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/torid-1.2.4/lib/torid/generator.rb:74:in `gethostbyname'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/torid-1.2.4/lib/torid/generator.rb:74:in `create_node_id'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/torid-1.2.4/lib/torid/generator.rb:80:in `<class:Generator>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/torid-1.2.4/lib/torid/generator.rb:21:in `<module:Torid>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/torid-1.2.4/lib/torid/generator.rb:8:in `<top (required)>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/torid-1.2.4/lib/torid.rb:22:in `<top (required)>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:91:in `require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:86:in `each'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:86:in `block in require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:75:in `each'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:75:in `require'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler.rb:106:in `require'
/Users/October/Documents/code/clients-api/config/application.rb:16:in `<top (required)>'
/Users/October/Documents/code/clients-api/config/environment.rb:2:in `require'
/Users/October/Documents/code/clients-api/config/environment.rb:2:in `<top (required)>'
/Users/October/Documents/code/clients-api/spec/spec_helper.rb:6:in `require'
/Users/October/Documents/code/clients-api/spec/spec_helper.rb:6:in `<top (required)>'
/Users/October/Documents/code/clients-api/spec/consumers/postback_notifier_consumer_spec.rb:1:in `require_relative'
/Users/October/Documents/code/clients-api/spec/consumers/postback_notifier_consumer_spec.rb:1:in `<top (required)>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/rspec:23:in `load'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/rspec:23:in `<main>'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/ruby_executable_hooks:15:in `eval'
/Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/ruby_executable_hooks:15:in `<main>'
Bundler Error Backtrace:
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:86:in `each'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:86:in `block in require'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:75:in `each'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler/runtime.rb:75:in `require'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/bundler-1.13.2/lib/bundler.rb:106:in `require'
    from /Users/October/Documents/code/clients-api/config/application.rb:16:in `<top (required)>'
    from /Users/October/Documents/code/clients-api/config/environment.rb:2:in `require'
    from /Users/October/Documents/code/clients-api/config/environment.rb:2:in `<top (required)>'
    from /Users/October/Documents/code/clients-api/spec/spec_helper.rb:6:in `require'
    from /Users/October/Documents/code/clients-api/spec/spec_helper.rb:6:in `<top (required)>'
    from /Users/October/Documents/code/clients-api/spec/consumers/postback_notifier_consumer_spec.rb:1:in `require_relative'
    from /Users/October/Documents/code/clients-api/spec/consumers/postback_notifier_consumer_spec.rb:1:in `<top (required)>'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/rspec:23:in `load'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/rspec:23:in `<main>'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/ruby_executable_hooks:15:in `eval'
    from /Users/October/.rvm/gems/ruby-2.3.1@clients-api/bin/ruby_executable_hooks:15:in `<main>'` 

I was able to confirm that in the actual torid gem, `Socket.gethostname` correctly returns my hostname, but breaks when trying to run this line: `hostname = Socket.gethostbyname( Socket.gethostname ).first` => `SocketError Exception: getaddrinfo: nodename nor servname provided, or not known
nil`

I'm not sure if this does have something to do with the torid gem itself, or honestly if someone just can understand what's going on I'd be extremely grateful. Thanks again!

**Comment by copiousfreetime** [comment]
What this is doing is getting a dns lookup for your hostname of your machine. This means that something is going oddly on the DNS resolution side of things.

Can you run the following on your machine and paste the output here?

`ruby -rsocket -e 'puts Addrinfo.getaddrinfo( Socket.gethostname, 0).first.getnameinfo.first'`

**Comment by OktoberComstock** [comment]
Thanks for getting back! Here is the output I got:

```ruby -rsocket -e 'puts Addrinfo.getaddrinfo( Socket.gethostname, 0).first.getnameinfo.first'```
=>
```-e:1:in `getaddrinfo': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from -e:1:in `<main>'```

I also saw a some other people having issues with the `Socket.gethostbyname()` method after updating to Sierra, I don't know if this helps, but here is the issue I posted on StackOverflow: http://stackoverflow.com/questions/39968792/socket-gethostbyname-unable-to-find-local-hostname-after-updating-to-mac-osx-sie

Someone using Python also had a similar error with that method: http://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie

**Comment by copiousfreetime** [comment]
Well dang, if I had a laptop running Sierra I would be able to figure this out. It looks like this is definitely a Sierra issue, and not a ruby issue.

I've written a C program to test this out on my laptop, if you would, please compile it and run it on sierra and let me know what the output is:

https://gist.github.com/copiousfreetime/44a950fb0fa8896450af75f919dbe7f1

**Comment by copiousfreetime** [comment]
@OktoberComstock I've updated a spare laptop to OSX Sierra and attempted to replicate what you experienced. Unfortunately my laptop doesn't show the same thing that you see. If you could run the following it might help debug what is going on.

```
require 'socket'

hostname = Socket.gethostname
Addrinfo.getaddrinfo( hostname, 0).each do |a|
  begin
    puts "Addrinfo: #{a.inspect}"
    names = a.getnameinfo
    puts "Names: #{names.inspect}"
  rescue => e
    puts "Error doing getnameinfo : #{e.inspect}"
  end
end
```

**Comment by OktoberComstock** [comment]
@copiousfreetime I ended up installing Docker and that did the trick. I never found out what the real issue was, but maybe this will help someone out there with the same issue figure it out. Thanks for getting back and being so helpful. 👍

**Comment by dmuneras** [comment]
@OktoberComstock  Have you already found the real problem?

**Comment by copiousfreetime** [comment]
@dmuneras it has to do with the hostname not being guaranteed to be round tripable through name resolution locally on a MacOS Sierra machine.  See 5dd4b36f982a846ab9bb7559e96ef8750994790d

My apologies for not closing this as fixed. Version 1.2.5 has been available since Dec 1 which fixes this.

**Comment by dmuneras** [comment]
@copiousfreetime  thanks a lot for your quick response, it save me a lot of time.

ASIDE: Happy new year

**Comment by jmtame** [comment]
This can also happen at certain cafe wifi networks.

**Comment by alicextt** [comment]
i am running el caption. also seeing this issue...

**Comment by copiousfreetime** [comment]
@jmtame @alicextt are you seeing this on the latest torid? And can you compile and run this program on your respective machines and post the output here ? - https://gist.github.com/copiousfreetime/44a950fb0fa8896450af75f919dbe7f1

**Comment by granowski-bamboo** [comment]
@copiousfreetime I compiled and ran your program since I'm running into this issue today (lol, in the year 2020)...
This is the output (I've replaced my real hostname with this fake text, since this is a work machine).

Hostname: THISISMYMACHINENAME
Error on getaddrinfo("THISISMYMACHINENAME", "0", &hits, &result)
Error on gethostbyname: Unknown host
